In [1]:
a = np.array([42, 44])

NameError: name 'np' is not defined

In [1]:
import numpy as np

In [3]:
a = np.array([42, 44])

In [4]:
a

array([42, 44])

In [5]:
a[-1]

44

In [6]:
a[-1]=0

In [7]:
a = np.random.randn(3)

In [8]:
a

array([-1.83295604, -3.00193089,  0.80358132])

In [9]:
b = a

In [10]:
b[0] = 0.0

In [11]:
a

array([ 0.        , -3.00193089,  0.80358132])

In [12]:
b = np.empty_like(a)

In [13]:
b

array([ 0.,  0.,  0.])

In [14]:
np.copyto(b,a)

In [15]:
b

array([ 0.        , -3.00193089,  0.80358132])

In [16]:
b[2] = 0

In [17]:
a

array([ 0.        , -3.00193089,  0.80358132])

In [18]:
b

array([ 0.        , -3.00193089,  0.        ])

In [19]:
z = np.array([1, 2, 3])

In [20]:
np.sin(z)

array([ 0.84147098,  0.90929743,  0.14112001])

In [21]:
for i in range(n):
    y[i] = np.sin(z[i])

NameError: name 'n' is not defined

In [2]:
import numpy as np

In [3]:
a=np.array([(1,2),(3,4)])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [6]:
b=np.matrix(a)

In [7]:
b

matrix([[1, 2],
        [3, 4]])

In [8]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [9]:
b * b

matrix([[ 7, 10],
        [15, 22]])

In [11]:
a.T

array([[1, 3],
       [2, 4]])

In [12]:
b.T

matrix([[1, 3],
        [2, 4]])

In [13]:
a.shape

(2, 2)

In [14]:
a = np.array([1,1])

In [15]:
a.shape

(2,)

In [16]:
a.reshape(2,1)

array([[1],
       [1]])

In [7]:
a = "十時"
print(a)

十時


In [13]:
print(float(0.00000000000005))

5e-14


In [3]:
aux = np.zeros(3)

In [4]:
print(aux)

[ 0.  0.  0.]


In [12]:
au= np.dot([3,2],[4,5])

In [10]:
print(au)

22
