In [2]:
import numpy as np

In [2]:
z = np.empty(3)

In [3]:
z

array([  2.46695025e+179,   1.02435731e-259,   4.94065646e-323])

In [4]:
z =np.identity(2)

In [5]:
z

array([[ 1.,  0.],
       [ 0.,  1.]])

In [6]:
type(z)

numpy.ndarray

In [7]:
z = np.array((10,20), dtype=float)

In [8]:
z

array([ 10.,  20.])

In [11]:
z= np.array([[1, 2],[3, 4]])

In [12]:
z

array([[1, 2],
       [3, 4]])

In [13]:
na = np.linspace(10, 20, 2)

In [14]:
na is np.asarray(na)

True

In [15]:
na is np.array(na
    )

False

In [16]:
na

array([ 10.,  20.])

In [19]:
na = np.linspace(0,10,21)

In [20]:
na

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ])

In [22]:
z = np.linspace(1, 2, 5)

In [23]:
z

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [24]:
z[0]

1.0

In [25]:
z[0:2]

array([ 1.  ,  1.25])

In [26]:
z[-1]

2.0

In [28]:
z = np.array([[1,2],[3,4]])

In [29]:
z[0,1]

2

In [30]:
z[1,0]

3

In [31]:
z[0,:]

array([1, 2])

In [32]:
z[:,1]

array([2, 4])

In [33]:
z[1,:]

array([3, 4])

In [34]:
z = np.linspace(2, 4, 5)

In [35]:
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [36]:
indices = np.array((0,2,3))

In [37]:
z[indices]

array([ 2. ,  3. ,  3.5])

In [38]:
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [39]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)

In [40]:
d

array([False,  True,  True, False, False], dtype=bool)

In [41]:
z[d]

array([ 2.5,  3. ])

In [42]:
z = np.empty(3)

In [43]:
z

array([ 0.,  0.,  0.])

In [44]:
z[:] = 42

In [45]:
z

array([ 42.,  42.,  42.])

In [46]:
A = np.array((4, 3, 2, 1))

In [47]:
A

array([4, 3, 2, 1])

In [48]:
A.sort()

In [49]:
A

array([1, 2, 3, 4])

In [50]:
A.sum()

10

In [51]:
A.mean()

2.5

In [52]:
A.argmax()

3

In [54]:
A.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [55]:
A.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [56]:
A.var()

1.25

In [57]:
A.std()

1.1180339887498949

In [58]:
A.shape =(2,2)

In [59]:
A.T

array([[1, 3],
       [2, 4]])

In [60]:
A

array([[1, 2],
       [3, 4]])

In [61]:
z =np.linspace(2,4,5)

In [62]:
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [63]:
z.searchsorted(2.4)

1

In [64]:
z.searchsorted(2.9)

2

In [65]:
a.sum

NameError: name 'a' is not defined

In [66]:
a.sum()

NameError: name 'a' is not defined

In [67]:
A.sum()

10

In [68]:
np.sum(A)

10

In [69]:
a = np.array([1,2,3,4])

In [70]:
b = np.array([5,6,7,8])

In [71]:
a + b

array([ 6,  8, 10, 12])

In [72]:
a * b

array([ 5, 12, 21, 32])

In [73]:
a + 10

array([11, 12, 13, 14])

In [74]:
a

array([1, 2, 3, 4])

In [75]:
a * 10

array([10, 20, 30, 40])

In [76]:
A = np.ones((2, 2))

In [77]:
B = np.ones((2, 2))

In [78]:
A + B

array([[ 2.,  2.],
       [ 2.,  2.]])

In [79]:
A

array([[ 1.,  1.],
       [ 1.,  1.]])

In [80]:
A * B

array([[ 1.,  1.],
       [ 1.,  1.]])

In [81]:
A @ B

array([[ 2.,  2.],
       [ 2.,  2.]])

In [83]:
A = np.ones((3,3))

In [84]:
A @ A

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [85]:
A = np.ones((2,3))

In [86]:
A @ A

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [88]:
B = np.ones((3,2))

In [89]:
A @ B

array([[ 3.,  3.],
       [ 3.,  3.]])

In [90]:
B @ A

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [3]:
a =np.array([1,1])
np.append(a,[1,2])

array([1, 1, 1, 2])

In [5]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[3,4]])

In [8]:
np.concatenate((c,d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [3, 4]])